import type { AppData } from "./types";

export const SEED: AppData = {
  technicians: Array.from({ length: 10 }, (_, i) => ({
    id: `T${String(i + 1).padStart(2, "0")}`,
    name: `Técnico ${String(i + 1).padStart(2, "0")}`,
    active: true,
  })),
  locations: [
    { id: "loc-base", name: "Santiago (base)", zone: "Centro", workType: "Traslado", equipment: 0 },
    { id: "loc-stgo", name: "Santiago", zone: "Centro", workType: "Instalación y capacitación", equipment: 3 },
    { id: "loc-valpo", name: "Valparaíso", zone: "Norte", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-cop", name: "Copiapó", zone: "Norte", workType: "Instalación y capacitación", equipment: 5 },
    { id: "loc-coq", name: "Coquimbo", zone: "Norte", workType: "Instalación y capacitación", equipment: 2 },
    { id: "loc-cal", name: "La Calera", zone: "Norte", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-sa", name: "San Antonio", zone: "Norte", workType: "Instalación y capacitación", equipment: 2 },
    { id: "loc-mel", name: "Melipilla", zone: "Centro", workType: "Instalación y capacitación", equipment: 2 },
    { id: "loc-lb", name: "Lo Barnechea", zone: "Centro", workType: "Instalación y capacitación", equipment: 3 },
    { id: "loc-pa", name: "Puente Alto", zone: "Centro", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-pud", name: "Pudahuel", zone: "Centro", workType: "Instalación y capacitación", equipment: 3 },
    { id: "loc-mai", name: "Maipú", zone: "Centro", workType: "Instalación y capacitación", equipment: 3 },
    { id: "loc-cur", name: "Curicó", zone: "Sur", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-tal", name: "Talca", zone: "Sur", workType: "Instalación y capacitación", equipment: 3 },
    { id: "loc-sp", name: "San Pedro de la Paz", zone: "Sur", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-pen", name: "Penco", zone: "Sur", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-tom", name: "Tomé", zone: "Sur", workType: "Instalación y capacitación", equipment: 1 },
    { id: "loc-sj", name: "Santa Juana", zone: "Sur", workType: "Instalación y capacitación", equipment: 1 },
  ],
  vehicles: Array.from({ length: 6 }, (_, i) => ({
    id: `v${i + 1}`,
    name: `Partner ${i + 1}`,
    plate: "",
  })),
  routes: [
    { id: "R-001", day: "Lunes", leadId: "T05" },
    { id: "R-002", day: "Lunes", leadId: "T01" },
  ],
  stops: [
    { id: "s1", routeId: "R-001", order: 1, locationId: "loc-base", workType: "Traslado", time: "08:00" },
    { id: "s2", routeId: "R-001", order: 2, locationId: "loc-valpo", workType: "Instalación y capacitación", time: "10:00" },
    { id: "s3", routeId: "R-001", order: 3, locationId: "loc-base", workType: "Traslado", time: "16:00" },
    { id: "s4", routeId: "R-002", order: 1, locationId: "loc-base", workType: "Traslado", time: "06:00" },
    { id: "s5", routeId: "R-002", order: 2, locationId: "loc-cop", workType: "Traslado", time: "15:00" },
  ],
  assignments: [
    {
      id: "a1",
      routeId: "R-001",
      technicianId: "T05",
      vehicleId: "v5",
      mode: "Individual",
      peopleInVan: 1,
      peopleOnRoute: 1,
      perDiem: 10000,
    },
    {
      id: "a2",
      routeId: "R-002",
      technicianId: "T01",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
    {
      id: "a3",
      routeId: "R-002",
      technicianId: "T02",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
    {
      id: "a4",
      routeId: "R-002",
      technicianId: "T03",
      vehicleId: "v2",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
    {
      id: "a5",
      routeId: "R-002",
      technicianId: "T04",
      vehicleId: "v2",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
  ],
};
