import {
  ADMIN_EMAIL,
  ADMIN_PASSWORD_HASH,
  emailFromName,
  makeAccount,
} from "./auth";
import { upcomingWeekday } from "./calendar";
import { regionLocations } from "./regions";
import type { Account, AppData } from "./types";

export const SEED_TECHNICIANS = [
  "Matías Abello",
  "Maximiliano Berríos",
  "Benjamín Bustos",
  "Christian Cáceres",
  "Camila Díaz",
  "Sebastián Gutiérrez",
  "Benjamín Martínez",
  "Fabián Ríos",
  "Abel Rocha",
  "Jeremías Villegas",
] as const;

const JEFATURA_SEED = [
  {
    id: "u-pablo",
    name: "Pablo Leiva",
    phone: "+56 9 6123 4501",
    title: "Coordinador de operaciones",
  },
  {
    id: "u-francisca",
    name: "Francisca Lagos",
    phone: "+56 9 6123 4502",
    title: "Jefa de despacho",
  },
  {
    id: "u-victor",
    name: "Víctor Godoy",
    phone: "+56 9 6123 4503",
    title: "Supervisor de terreno",
  },
] as const;

function seedAccounts(): Account[] {
  const admin = makeAccount({
    id: "u-admin",
    email: ADMIN_EMAIL,
    role: "admin",
    name: "Administrador",
    phone: "+56 9 2000 0001",
    title: "Administración de cuentas",
    passwordHash: ADMIN_PASSWORD_HASH,
  });
  const jefatura = JEFATURA_SEED.map((person) =>
    makeAccount({
      ...person,
      email: emailFromName(person.name),
      role: "jefatura",
    }),
  );
  const technicians = SEED_TECHNICIANS.map((name, i) =>
    makeAccount({
      id: `u-t${String(i + 1).padStart(2, "0")}`,
      email: emailFromName(name),
      role: "tecnico",
      name,
      phone: `+56 9 7${String(100 + i).slice(-3)} ${String(4500 + i * 17).slice(-4)}`,
      title: "Técnico de terreno",
      technicianId: `T${String(i + 1).padStart(2, "0")}`,
    }),
  );
  return [admin, ...jefatura, ...technicians];
}

export const SEED: AppData = {
  technicians: SEED_TECHNICIANS.map((name, i) => ({
    id: `T${String(i + 1).padStart(2, "0")}`,
    name,
    active: true,
  })),
  locations: regionLocations(),
  vehicles: [
    { id: "v1", name: "Partner", model: "Partner", kind: "Camioneta", plate: "ABCD10", status: "operativo" },
    { id: "v2", name: "Partner", model: "Partner", kind: "Camioneta", plate: "ABCD11", status: "operativo" },
    { id: "v3", name: "Berlingo", model: "Berlingo", kind: "Furgón", plate: "ABCD12", status: "operativo" },
    { id: "v4", name: "Hilux", model: "Hilux", kind: "Camioneta", plate: "ABCD13", status: "operativo" },
    { id: "v5", name: "Partner", model: "Partner", kind: "Camioneta", plate: "ABCD14", status: "operativo" },
    { id: "v6", name: "Ranger", model: "Ranger", kind: "Camioneta", plate: "ABCD15", status: "fuera_de_servicio" },
  ],
  routes: [
    {
      id: "R-001",
      day: "Lunes",
      date: upcomingWeekday("Lunes"),
      leadId: "T05",
      vehicleId: "v5",
      status: "abierta",
      allowances: {
        breakfast: 0,
        lunch: 10000,
        dinner: 0,
        tolls: 3500,
        fuel: 18000,
        hotel: 0,
      },
    },
    {
      id: "R-002",
      day: "Lunes",
      date: upcomingWeekday("Lunes"),
      leadId: "T01",
      vehicleId: "v1",
      status: "abierta",
      allowances: {
        breakfast: 6000,
        lunch: 10000,
        dinner: 8000,
        tolls: 12000,
        fuel: 45000,
        hotel: 52000,
      },
    },
  ],
  stops: [
    { id: "s1", routeId: "R-001", order: 1, locationId: "loc-base", workType: "Traslado", time: "08:00" },
    {
      id: "s2",
      routeId: "R-001",
      order: 2,
      locationId: "loc-valparaiso",
      city: "Valparaíso",
      workType: "Instalación y capacitación",
      time: "10:00",
      assigneeIds: ["T05"],
      installAddress: "Av. Argentina 2345, Valparaíso",
      installKind: "Cámaras y DVR",
      companyName: "Puerto Exterior S.A.",
      installStatus: "pendiente",
      workOrderId: "OT-001",
    },
    { id: "s3", routeId: "R-001", order: 3, locationId: "loc-base", workType: "Regreso a base", time: "16:00" },
    { id: "s4", routeId: "R-002", order: 1, locationId: "loc-base", workType: "Traslado", time: "06:00" },
    {
      id: "s5",
      routeId: "R-002",
      order: 2,
      locationId: "loc-atacama",
      city: "Copiapó",
      workType: "Traslado y pernocte",
      time: "15:00",
      lodgingPlan: "Hotel Diego de Almagro Copiapó",
      lodgingStatus: "pendiente",
    },
  ],
  assignments: [
    {
      id: "a1",
      routeId: "R-001",
      technicianId: "T05",
      vehicleId: "v5",
      mode: "Individual",
      peopleInVan: 1,
      peopleOnRoute: 1,
      perDiem: 10000,
    },
    {
      id: "a2",
      routeId: "R-002",
      technicianId: "T01",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 10000,
    },
    {
      id: "a3",
      routeId: "R-002",
      technicianId: "T02",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 10000,
    },
    {
      id: "a4",
      routeId: "R-002",
      technicianId: "T03",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 10000,
    },
    {
      id: "a5",
      routeId: "R-002",
      technicianId: "T04",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 10000,
    },
  ],
  progress: [],
  events: [],
  accounts: seedAccounts(),
  invites: [],
  workOrders: [
    {
      id: "OT-001",
      workType: "Instalación y capacitación",
      companyName: "Puerto Exterior S.A.",
      locationId: "loc-valparaiso",
      city: "Valparaíso",
      address: "Av. Argentina 2345, Valparaíso",
      installKind: "Cámaras y DVR",
      materials: [
        { id: "m1", label: "DVR 8 canales" },
        { id: "m2", label: "4 cámaras IP" },
        { id: "m3", label: "Cable UTP 20 m" },
        { id: "m4", label: "Taladro, tarugos y conectores" },
      ],
      status: "en_ruta",
      stopId: "s2",
      routeId: "R-001",
      createdAt: 1,
    },
    {
      id: "OT-002",
      workType: "Instalación",
      companyName: "Puerto Caldera Ltda.",
      locationId: "loc-atacama",
      city: "Copiapó",
      address: "Av. Copayapu 2101, Copiapó",
      installKind: "Alarma perimetral",
      materials: [
        { id: "m5", label: "Central de alarma" },
        { id: "m6", label: "6 sensores magnéticos" },
        { id: "m7", label: "Sirena exterior" },
        { id: "m8", label: "Cable y fuente 12 V" },
      ],
      status: "pendiente",
      createdAt: 1,
    },
    {
      id: "OT-003",
      workType: "Despacho",
      companyName: "Clínica del Valle",
      locationId: "loc-valparaiso",
      city: "Viña del Mar",
      address: "Av. Libertad 1348, Viña del Mar",
      installKind: "DVR y 4 cámaras",
      materials: [
        { id: "m9", label: "DVR" },
        { id: "m10", label: "4 cámaras" },
        { id: "m11", label: "Fuente 12 V" },
        { id: "m12", label: "Conectores BNC" },
      ],
      status: "pendiente",
      createdAt: 1,
    },
  ],
  updatedAt: 1,
};
