import { upcomingWeekday } from "./calendar";
import { regionLocations } from "./regions";
import type { AppData } from "./types";

export const SEED: AppData = {
  technicians: Array.from({ length: 10 }, (_, i) => ({
    id: `T${String(i + 1).padStart(2, "0")}`,
    name: `Técnico ${String(i + 1).padStart(2, "0")}`,
    active: true,
  })),
  locations: regionLocations(),
  vehicles: [
    { id: "v1", name: "Partner", model: "Partner", kind: "Camioneta", plate: "ABCD10", status: "operativo" },
    { id: "v2", name: "Partner", model: "Partner", kind: "Camioneta", plate: "ABCD11", status: "operativo" },
    { id: "v3", name: "Berlingo", model: "Berlingo", kind: "Furgón", plate: "ABCD12", status: "operativo" },
    { id: "v4", name: "Hilux", model: "Hilux", kind: "Camioneta", plate: "ABCD13", status: "operativo" },
    { id: "v5", name: "Partner", model: "Partner", kind: "Camioneta", plate: "ABCD14", status: "operativo" },
    { id: "v6", name: "Ranger", model: "Ranger", kind: "Camioneta", plate: "ABCD15", status: "fuera_de_servicio" },
  ],
  routes: [
    { id: "R-001", day: "Lunes", date: upcomingWeekday("Lunes"), leadId: "T05", vehicleId: "v5", status: "abierta" },
    { id: "R-002", day: "Lunes", date: upcomingWeekday("Lunes"), leadId: "T01", vehicleId: "v1", status: "abierta" },
  ],
  stops: [
    { id: "s1", routeId: "R-001", order: 1, locationId: "loc-base", workType: "Traslado", time: "08:00" },
    {
      id: "s2",
      routeId: "R-001",
      order: 2,
      locationId: "loc-valparaiso",
      city: "Valparaíso",
      workType: "Instalación y capacitación",
      time: "10:00",
      assigneeIds: ["T05"],
      installAddress: "Av. Argentina 2345, Valparaíso",
      installKind: "Cámaras y DVR",
      companyName: "Puerto Exterior S.A.",
      installStatus: "pendiente",
      workOrderId: "OT-001",
    },
    { id: "s3", routeId: "R-001", order: 3, locationId: "loc-base", workType: "Regreso a base", time: "16:00" },
    { id: "s4", routeId: "R-002", order: 1, locationId: "loc-base", workType: "Traslado", time: "06:00" },
    {
      id: "s5",
      routeId: "R-002",
      order: 2,
      locationId: "loc-atacama",
      city: "Copiapó",
      workType: "Traslado y pernocte",
      time: "15:00",
      lodgingPlan: "Hotel Diego de Almagro Copiapó",
      lodgingStatus: "pendiente",
    },
  ],
  assignments: [
    {
      id: "a1",
      routeId: "R-001",
      technicianId: "T05",
      vehicleId: "v5",
      mode: "Individual",
      peopleInVan: 1,
      peopleOnRoute: 1,
      perDiem: 10000,
    },
    {
      id: "a2",
      routeId: "R-002",
      technicianId: "T01",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
    {
      id: "a3",
      routeId: "R-002",
      technicianId: "T02",
      vehicleId: "v1",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
    {
      id: "a4",
      routeId: "R-002",
      technicianId: "T03",
      vehicleId: "v2",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
    {
      id: "a5",
      routeId: "R-002",
      technicianId: "T04",
      vehicleId: "v2",
      mode: "Grupal",
      peopleInVan: 2,
      peopleOnRoute: 4,
      perDiem: 20000,
    },
  ],
  progress: [],
  events: [],
  workOrders: [
    {
      id: "OT-001",
      workType: "Instalación y capacitación",
      companyName: "Puerto Exterior S.A.",
      locationId: "loc-valparaiso",
      city: "Valparaíso",
      address: "Av. Argentina 2345, Valparaíso",
      installKind: "Cámaras y DVR",
      status: "en_ruta",
      stopId: "s2",
      routeId: "R-001",
      createdAt: 1,
    },
    {
      id: "OT-002",
      workType: "Instalación",
      companyName: "Puerto Caldera Ltda.",
      locationId: "loc-atacama",
      city: "Copiapó",
      address: "Av. Copayapu 2101, Copiapó",
      installKind: "Alarma perimetral",
      status: "pendiente",
      createdAt: 1,
    },
    {
      id: "OT-003",
      workType: "Despacho",
      companyName: "Clínica del Valle",
      locationId: "loc-valparaiso",
      city: "Viña del Mar",
      address: "Av. Libertad 1348, Viña del Mar",
      installKind: "DVR y 4 cámaras",
      status: "pendiente",
      createdAt: 1,
    },
  ],
  updatedAt: 1,
};
